# Change these first
owner: ditchthis # Your GitHub organization or username, where this repository lives
repo: upptime-monitoring # The name of this repository

sites:
  - name: DitchCarbon
    url: https://ditchcarbon.com/
  - name: DitchCarbon Docs
    url: https://docs.ditchcarbon.com/
  - name: DitchCarbon API
    url: https://api.ditchcarbon.com/industries
    headers:
      - "Authorization: Bearer $DC_API_KEY"
      - "Content-Type: application/json"

assignees:
  davelush-dc
#  penguoir
#  CharlieGroves

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#  cname: demo.upptime.js.org
  baseUrl: /upptime-monitoring
  logoUrl: https://files.readme.io/d3ad520-small-Logo_branding_kit_Favicon_Square_1.png
  name: DitchCarbon Status
  introTitle: "**DitchCarbon** status and uptime."
  introMessage: This page shows the status of all of our services at DitchCarbon. We will also share details of any live incidents and resolutions as they occur.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
